(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(*These list all optional arguments for all PowerGrid functions in use and a short explanation of what they do*)
PowerGridOptionDescription=
"\!\(\*
StyleBox[\"Relevant\",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\" \",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\"for\",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\" \",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\"most\",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\" \",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\"PowerGrid\",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\" \",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\"functions\",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\":\",\nFontWeight->\"Plain\"]\)
inputDirectory specifies the Directory from where to import data
couplingMatrix, powerVector and inertiaVector can either be strings to import from inputDirectory or can be given as explicit lists 
damping\[Alpha] specifies the intrinsic damping (scalar or vector)
tmin and tmax specify the minimum and maximum simulation time respectively
priceElasticity\[Gamma] specifies the price elasticity (scalar or vector) 
delay\[Tau] specifies the delay of the system (scalar or vector)
averagingTime specifies the averaging period(scalar or vector)
seedRandom sets the RandomGenerator to a given seed. This is used to generate random initial conditions if needed and then the RandomGenerator is reset again.
exportResults has to be set to True to output results to file \!\(\*
StyleBox[\"outputName\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\" \",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\"\\\\n\",\nFontWeight->\"Plain\"]\)startingPoint specifies where the Newton algorithm should start its search for the fixed point, (default: 0-vector)\!\(\*
StyleBox[\"\\\\n\",\nFontWeight->\"Plain\"]\)defaultMessage->True warns the user by Print-commands about random initial conditions and default network topologies being used.\!\(\*
StyleBox[\"\\\\n\",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\"\\\\n\",\nFontWeight->\"Plain\"]\)\!\(\*
StyleBox[\"P\",\nFontWeight->\"Plain\"]\)owerGridCharacteristicEquation:
useFixedPoint determines whether PowerGridFixedPoint[] shall be called to numerically determine the fixed point (all options will be passed)
useAveraging allows to set the average time T to zero before attempting to formulate the characteristic equation

PowerGridSolver: 
perturbations[[i]] adds an additional term to the ith equation of motion
angle\[Theta]0min,angle\[Theta]0max,angularVelocity\[Omega]0min,angularVelocity\[Omega]0max specify the ranges for random initial conditions 
exportPertubations has to be set to True to output perturbations, Note: random process functions are lage to store
exportTrajectory exports the trajectory as a part of the output, only works when using WDX format
initialCondition can be a string to import from inputDirectory, can be given as an explicit list or can be set to 'FixedPoint'
frequencyOffset can be used to change the initial frequency of node 1.
exportFormat can be chosed between WDX and h5. WDX is more efficient, h5 was inspired by Potsdam people.

events can be used to establish WhenEvent rules, it has to be given as a list (PowerGridSolverAdaptivePower only)
powerDynamics sets the dynaics of the power of each node (PowerGridSolverAdaptivePower only)

In case of no input one producer and one consumer are used as the default case for all PowerGrid functions. 
";


(* ::Input::Initialization:: *)
(*Power Grid Fixed Point*)
PowerGridFixedPoint::usage="PowerGridFixedPoint[] takes no argument and returns a transformation rule coding one fixed point of a power grid system, similar to FindRoot. Note that the result depends on the starting point. The fixed point still can be shifted by an arbitrary amount in all angle\[Theta]. If the result is not a fixed point, it returns a text message.
It takes all FindRoot options and some power grid specific ones: \n"<>PowerGridOptionDescription;

(*Power Grid Solver*)
PowerGridSolver::usage="PowerGridSolver[] takes no argument and returns a replacement rule as the solution of a power grid system, similar to NDSolve. 
Now also offers inverter dynamics as an additional option.
It takes all NDSolve options and some power grid specific ones: \n"<>PowerGridOptionDescription;

(*Power Grid Solver with adaptive power*)
PowerGridSolverAdaptivePower::usage="PowerGridSolverAdaptivePower[] takes no argument and returns a replacement rule as the solution of a power grid system, similar to NDSolve. 
Compared to PowerGridSolver it cannot handle price elasticity; Instead it uses the function powerDynamics to influence the dynamics of the power vector directly.
In addition the initial condition needs information for the powerEntries[i][0] as they are additional variables.
It takes all NDSolve options and some power grid specific ones: \n"<>PowerGridOptionDescription;

(*PowerGridCascadeSimulation*)
PowerGridCascadeSimulation::usage="Simulate power grid cascades.
Specific options:
calculateMeasures-> True will output all measures as a list.
generateVisualizations->True will instead output figures of the angularVelocity plotted over time. in addition the final network will be shown.
minimumTransientOverloadTime sets the minimum time a line has to be overloaded before it is cut.
triggerLine and triggerTime determine the trigger event to set off the cascade. Simply set triggerTime>tmax to avoid a line being cut.
powerOffset is another option to set the system apart from the fixed point initially.
tolerance\[Alpha] gives the factor to which a line can be overloaded before it shuts down.
useInitialFlowThreshold switches between applying the absolute lineThreshold and the relative tolerance\[Alpha]
useCascadingRules can be set to False to observe how the system would have evolved without addiiontal line cuts
\[Omega]NodeNotSynchronized is the threshold for which I assume a node to be not synchronized at tmax.
It takes power grid specific Options: \n"<>PowerGridOptionDescription;



(* ::Input::Initialization:: *)
(*PowerGridInput: Take all optional arguments and convert them into a form to be used by other functions*)
PowerGridInput::usage="PowerGridInput[] takes no argument and does return nothing. However, it is included in all PowerGrid functions to handle the optional input and generate default cases when necessary."<>PowerGridOptionDescription;
Options[PowerGridInput]={
adaptationProportionalToPower->False,
adaptationRate->0.4/(2*N[\[Pi]]),
angle\[Theta]0max->N[Pi],
angle\[Theta]0min->-N[Pi],
angularVelocity\[Omega]0max->20.,
angularVelocity\[Omega]0min->-20.,
averagingTime->0,
calculateMeasures->True,
couplingMatrix->{{0,1},{1,0}},
cutOff->-10,
damping\[Alpha]->0.1`,
defaultMessage->False,
delay\[Tau]->0.,
endConstantInterval->0.2*2*\[Pi],
events->{},
exportFormat->"WDX",
exportPertubations->False,
exportResults->False,
exportTrajectory->False,
frequencyOffset->0,
generateVisualizations->False,
inertiaVector->0,
initialCondition->0,
inputDirectory:>NotebookDirectory[],
listOfAveragingTimes->{0,1,2,4},
maxDelay\[Tau]->2,
measurementBias->0,
minimumTransientOverloadTime->0,
numberOfTrysForMinimalDelay->1000,
offSet->0.,
perturbations->0,
phaseShiftMatrix->0,
powerVector->{-1,1},
powerOffset->0,
powerDynamics->0,
priceElasticity\[Gamma]->0,
returnCouplingOnly->False,
samplingDelay\[Tau]->0,
secondaryControl->0,
seedRandom->{},
startConstantInterval->-0.2*2*\[Pi],
startingPoint->None,
stepsizeDelay\[Tau]->0.01,
subFigureLegend->"(a)",
textPosition->{-1,1},
tmax->10,
tmin->0,
tolerance\[Alpha]->1.5,
triggerLine->{1,2},
triggerTime->1,
useInitialFlowThreshold->False,
useangle\[Theta]1Equal0->True,
useAveraging->False,
useCascadingRules->True,
useFixedPoint->True,
useGridGraph->False,
useInverterDynamics->False,
useLinearizedSwing->False,
useReduce->True,
vertexLabelSize->12,
\[Omega]NodeNotSynchronized->0.02*2*Pi,
outputDirectory:>NotebookDirectory[],
voltageCouplingX->1,
voltageTimeScale->2,
voltageSetPoint->1,
startingVoltage->1,
fixedPointValidationThreshold->10^-10,
useVoltageAmplitude->False,
outputName:>"Swing equation solved or Eigenvalues"<>DateString["Year"]<>"."<>DateString["Month"]<>"."<>DateString["Day"]<>"_"<>DateString["Hour"]<>"."<>DateString["Minute"]<>"."<>DateString["Second"]
(*outputName\[RuleDelayed]"Eigenvalues "<>DateString["Year"]<>"."<>DateString["Month"]<>"."<>DateString["Day"]<>"_"<>DateString["Hour"]<>"."<>DateString["Minute"]<>"."<>DateString["Second"],outputName\[RuleDelayed]"Swing equation solved "<>DateString["Year"]<>"."<>DateString["Month"]<>"."<>DateString["Day"]<>"_"<>DateString["Hour"]<>"."<>DateString["Minute"]<>"."<>DateString["Second"]*)
};
(*Start the "PowerGrid" Context*)
Begin["PowerGrid`"];
PowerGridInput[opts:OptionsPattern[]]:=
With[{},
(*Evaluate that all OptionValues are assigned to a qunatity named optionNameInput*)
adaptationProportionalToPowerInput=OptionValue[adaptationProportionalToPower];adaptationRateInput=OptionValue[adaptationRate];angle\[Theta]0maxInput=OptionValue[angle\[Theta]0max];angle\[Theta]0minInput=OptionValue[angle\[Theta]0min];angularVelocity\[Omega]0maxInput=OptionValue[angularVelocity\[Omega]0max];angularVelocity\[Omega]0minInput=OptionValue[angularVelocity\[Omega]0min];averagingTimeInput=OptionValue[averagingTime];calculateMeasuresInput=OptionValue[calculateMeasures];couplingMatrixInput=OptionValue[couplingMatrix];cutOffInput=OptionValue[cutOff];damping\[Alpha]Input=OptionValue[damping\[Alpha]];defaultMessageInput=OptionValue[defaultMessage];delay\[Tau]Input=OptionValue[delay\[Tau]];endConstantIntervalInput=OptionValue[endConstantInterval];eventsInput=OptionValue[events];exportFormatInput=OptionValue[exportFormat];exportPertubationsInput=OptionValue[exportPertubations];exportResultsInput=OptionValue[exportResults];frequencyOffsetInput=OptionValue[frequencyOffset];exportTrajectoryInput=OptionValue[exportTrajectory];
generateVisualizationsInput=OptionValue[generateVisualizations];
inertiaVectorInput=OptionValue[inertiaVector];
initialConditionInput=OptionValue[initialCondition];
inputDirectoryInput=OptionValue[inputDirectory];
listOfAveragingTimesInput=OptionValue[listOfAveragingTimes];
maxDelay\[Tau]Input=OptionValue[maxDelay\[Tau]];
measurementBiasInput=OptionValue[measurementBias];
minimumTransientOverloadTimeInput=OptionValue[minimumTransientOverloadTime];
numberOfTrysForMinimalDelayInput=OptionValue[numberOfTrysForMinimalDelay];offSetInput=OptionValue[offSet];perturbationsInput=OptionValue[perturbations];
phaseShiftMatrixInput=OptionValue[phaseShiftMatrix];
powerVectorInput=OptionValue[powerVector];
powerDynamicsInput=OptionValue[powerDynamics];
powerOffsetInput=OptionValue[powerOffset];
priceElasticity\[Gamma]Input=OptionValue[priceElasticity\[Gamma]];priceElasticity\[Gamma]Input=OptionValue[priceElasticity\[Gamma]];returnCouplingOnlyInput=OptionValue[returnCouplingOnly];samplingDelay\[Tau]Input=OptionValue[samplingDelay\[Tau]];
secondaryControlInput=OptionValue[secondaryControl];
seedRandomInput=OptionValue[seedRandom];
startConstantIntervalInput=OptionValue[startConstantInterval];startingPointInput=OptionValue[startingPoint];stepsizeDelay\[Tau]Input=OptionValue[stepsizeDelay\[Tau]];subFigureLegendInput=OptionValue[subFigureLegend];textPositionInput=OptionValue[textPosition];tmaxInput=OptionValue[tmax];tminInput=OptionValue[tmin];tolerance\[Alpha]Input=OptionValue[tolerance\[Alpha]];
triggerLineInput=OptionValue[triggerLine];
triggerTimeInput=OptionValue[triggerTime];
useInitialFlowThresholdInput=OptionValue[useInitialFlowThreshold];
useangle\[Theta]1Equal0Input=OptionValue[useangle\[Theta]1Equal0];useAveragingInput=OptionValue[useAveraging];useCascadingRulesInput=OptionValue[useCascadingRules];useFixedPointInput=OptionValue[useFixedPoint];useGridGraphInput=OptionValue[useGridGraph];useInverterDynamicsInput=OptionValue[useInverterDynamics];
useLinearizedSwingInput=OptionValue[useLinearizedSwing];
useReduceInput=OptionValue[useReduce];vertexLabelSizeInput=OptionValue[vertexLabelSize];\[Omega]NodeNotSynchronizedInput=OptionValue[\[Omega]NodeNotSynchronized];
outputDirectoryInput=OptionValue[outputDirectory];outputNameInput=OptionValue[outputName];
fixedPointValidationThresholdInput=OptionValue[fixedPointValidationThreshold];
useVoltageAmplitudeInput=OptionValue[useVoltageAmplitude];
(*Trying to Automate the assignement Not working*)
(* (*Import all option names*)
optionNames=Apply[List,Options[PowerGridInput],2][[;;,1]];
Map[ToExpression,Map["PowerGridAuxilary`"<>ToString[#]<>"Input="<>ToString[OptionValue[#]]&,optionNames]];*)
(*Kind of working*)
(*ToExpression["PowerGridAuxilary`useGridGraphInput="<>ToString[OptionValue[useGridGraph]]];*)
(*Modify some imported variables and deduces new ones, e.g. numberOfNodes*)

couplingMatrixInput=Which[
StringQ[couplingMatrixInput],SetDirectory[inputDirectoryInput];Import[couplingMatrixInput,"Table"],
SymmetricMatrixQ[couplingMatrixInput],couplingMatrixInput,
True,Print["Invalid couplingMatrix input. Must be String or symmetric matrix"];Return[]];
powerVectorInput=Which[
StringQ[powerVectorInput],SetDirectory[inputDirectoryInput];Import[powerVectorInput,"List"],
ListQ[powerVectorInput],powerVectorInput,
True,Print["Invalid powerVector input. Must be String or vector"];Return[]];
numberOfNodes=Length[powerVectorInput];
inertiaVectorInput=Which[
StringQ[inertiaVectorInput],SetDirectory[inputDirectoryInput];Import[inertiaVectorInput,"List"],
ListQ[inertiaVectorInput],inertiaVectorInput,
True,Table[1,{numberOfNodes}]];
measurementBiasInput=Which[
ListQ[measurementBiasInput],measurementBiasInput,
NumberQ[measurementBiasInput],Table[measurementBiasInput,{numberOfNodes}],
True,Table[0,{numberOfNodes}]];
phaseShiftMatrixInput=Which[
StringQ[phaseShiftMatrixInput],SetDirectory[inputDirectoryInput];Import[phaseShiftMatrixInput,"List"],
SymmetricMatrixQ[phaseShiftMatrixInput],phaseShiftMatrixInput,
True,Table[0,{numberOfNodes},{numberOfNodes}]];

voltageTimeScaleInput=OptionValue[voltageTimeScale];
voltageCouplingXInput=OptionValue[voltageCouplingX];
voltageSetPointInput=OptionValue[voltageSetPoint];
startingVoltageInput=OptionValue[startingVoltage];
voltageCouplingXInput=Which[ListQ[voltageCouplingXInput],voltageCouplingXInput,
NumberQ[voltageCouplingXInput],Table[voltageCouplingXInput,{numberOfNodes}]];
voltageSetPointInput=Which[ListQ[voltageSetPointInput],voltageSetPointInput,
NumberQ[voltageSetPointInput],Table[voltageSetPointInput,{numberOfNodes}]];
startingVoltageInput=Which[ListQ[startingVoltageInput],startingVoltageInput,
NumberQ[startingVoltageInput],Table[startingVoltageInput,{numberOfNodes}]];


(*Define starting point for Newtons method to find the fixed point*)
startingPointInput=Which[
StringQ[startingPointInput],SetDirectory[inputDirectoryInput];Import[startingPointInput,"Table"],
ListQ[startingPointInput],startingPointInput,
True,If[defaultMessageInput,Print["Using default starting point"]];Table[0,{numberOfNodes}]];
(*perform consistency checks of dimensions*)
Which[
Length[powerVectorInput]==Dimensions[couplingMatrixInput][[1]],Null,
True, Print["Dimensions of coupling matrix and power vector have to be identical \n"];
Return[Print[StringJoin["Current dimensions are:\n coupling matrix:", ToString[Dimensions[couplingMatrixInput]],"\n power vector:", ToString[Length[powerVectorInput]]]]];
];
damping\[Alpha]Input=Which[ListQ[damping\[Alpha]Input],damping\[Alpha]Input,
NumberQ[damping\[Alpha]Input],Table[damping\[Alpha]Input,{numberOfNodes}]];
secondaryControlInput=Which[ListQ[secondaryControlInput],secondaryControlInput,
NumberQ[secondaryControlInput],Table[secondaryControlInput,{numberOfNodes}]];
priceElasticity\[Gamma]Input=Which[ListQ[priceElasticity\[Gamma]Input],priceElasticity\[Gamma]Input,
NumberQ[priceElasticity\[Gamma]Input],Table[priceElasticity\[Gamma]Input,{numberOfNodes}]];
delay\[Tau]Input=Which[ListQ[delay\[Tau]Input],delay\[Tau]Input,
NumberQ[delay\[Tau]Input],Table[delay\[Tau]Input,{numberOfNodes}]];
averagingTimeInput=Which[ListQ[averagingTimeInput],averagingTimeInput,
NumberQ[averagingTimeInput],Table[averagingTimeInput,{numberOfNodes}]];
(*define initial conditions: Either read in, give the precise table or use randomly generated ones*)
initialConditionInput=
Which[
ListQ[initialConditionInput],initialConditionInput,
StringQ[initialConditionInput], If[initialConditionInput=="FixedPoint",initialConditionInput,
SetDirectory[inputDirectoryInput];Read[StringToStream[ToString[Import[initialConditionInput,"List",CharacterEncoding->"UTF8"]]]]],
initialConditionInput==0,Flatten@Table[{PowerGrid`angle\[Theta][i][PowerGrid`t/;PowerGrid`t<=0]==0,PowerGrid`angularVelocity\[Omega][i][PowerGrid`t/;PowerGrid`t<=0]==0},{i,1,numberOfNodes}],
True, 
If[defaultMessageInput,Print["Using random initial conditions"]];
SeedRandom[seedRandomInput];
randangle\[Theta]=RandomReal[{angle\[Theta]0minInput,angle\[Theta]0maxInput},numberOfNodes];randangularVelocity\[Omega]=RandomReal[{angularVelocity\[Omega]0minInput,angularVelocity\[Omega]0maxInput},numberOfNodes];
Flatten[Table[{angle\[Theta][i][ t/;t<= 0]== randangle\[Theta][[i]],angularVelocity\[Omega][i][ t/;t<= 0]==randangularVelocity\[Omega][[i]]*(1+Tanh[t/2])},{i,1,numberOfNodes}]]
];
(*add dynamical pertubations from file or as precise table*)
perturbationsInput=Which[
StringQ[perturbationsInput],SetDirectory[inputDirectoryInput];Read[StringToStream[ToString[Import[perturbationsInput,"List",CharacterEncoding->"UTF8"]]]],
ListQ[perturbationsInput],If[StringQ[perturbationsInput[[1]]],Map[ToExpression,perturbationsInput],perturbationsInput],
True, If[defaultMessageInput,Print["Perturbations need to be in List-form, using 0 perturbations"]];Table[0,{numberOfNodes}]
];
SeedRandom[seedRandomInput];
powerGridSolverCalledByCascades=False;
Return[]
]


(* ::Input::Initialization:: *)
(*Power Grid Fixed Point*)
Options[PowerGridFixedPoint]=Union[Options[FindRoot] ,Options[PowerGridInput]];
PowerGridFixedPoint[opts:OptionsPattern[]]:=
With[(*use local version of functions*)
{},
PowerGridInput[Evaluate[FilterRules[{opts}, Options[PowerGridInput]]]];
(*Numerically find one fixed point of the power grid, the equation was simplified, using angularVelocity\[Omega][t]=0*)
fixedPoint=If[Total[secondaryControlInput]==0,
Join[FindRoot[Evaluate[Table[powerVectorInput[[i]]+Sum[couplingMatrixInput[[i,j]]*Sin[angle\[Theta][j]-angle\[Theta][i]+phaseShiftMatrixInput[[i,j]]],{j,1,numberOfNodes}]-secondaryControlInput[[i]]*angle\[Theta][i]==0,{i,2,numberOfNodes}]\[Union]{angle\[Theta][1]==0}],Table[{angle\[Theta][i],startingPointInput[[i]]},{i,1,numberOfNodes}]
,Evaluate[FilterRules[{opts}, Options[FindRoot]]](*we need Evaluate[] since FindRoot[] has Attrbiute HoldAll*)
],Table[angularVelocity\[Omega][i]->0,{i,1,numberOfNodes}]]
,
Join[FindRoot[Evaluate[Table[powerVectorInput[[i]]+Sum[couplingMatrixInput[[i,j]]*Sin[angle\[Theta][j]-angle\[Theta][i]+phaseShiftMatrixInput[[i,j]]],{j,1,numberOfNodes}]-secondaryControlInput[[i]]*angle\[Theta][i]==0,{i,1,numberOfNodes}]],Table[{angle\[Theta][i],startingPointInput[[i]]},{i,1,numberOfNodes}]
,Evaluate[FilterRules[{opts}, Options[FindRoot]]](*we need Evaluate[] since FindRoot[] has Attrbiute HoldAll*)
],Table[angularVelocity\[Omega][i]->0,{i,1,numberOfNodes}]]];
validated=DeleteDuplicates@Table[Evaluate[Abs[powerVectorInput[[i]]+Sum[couplingMatrixInput[[i,j]]*Sin[angle\[Theta][j]-angle\[Theta][i]+phaseShiftMatrixInput[[i,j]]],{j,1,numberOfNodes}]-secondaryControlInput[[i]]*angle\[Theta][i]]/.fixedPoint]<10^-10,{i,1,numberOfNodes}];
If[validated==={True},
Return[fixedPoint],
Return["Fixed point could not be found"]]
]


(* ::Input::Initialization:: *)
(*Power Grid Solver*)
Options[PowerGridSolver]=Union[Options[NDSolve] ,Options[PowerGridInput]];
PowerGridSolver[opts:OptionsPattern[]]:=
Module[(*use local version of the function for the price*){price},
PowerGridInput[Evaluate[FilterRules[{opts}, Options[PowerGridInput]]]];
With[{(*define scalar variables as homogeneous lists*)
variables=Table[angle\[Theta][index],{index,1,numberOfNodes}]\[Union]Table[angularVelocity\[Omega][index],{index,1,numberOfNodes}]},
(*define price-frequency-relation, use averaging, if averagingTime[[i]]>0*)
If[useInverterDynamicsInput==False,
price[t_]:=Which[ 
Total[averagingTimeInput]==0,Table[-If[adaptationProportionalToPowerInput,Abs[powerVectorInput[[i]]],1]*priceElasticity\[Gamma]Input[[i]]*angularVelocity\[Omega][i][t-delay\[Tau]Input[[i]]],{i,1,numberOfNodes}],
True,Table[
Which[
averagingTimeInput[[i]]==0,-If[adaptationProportionalToPowerInput,Abs[powerVectorInput[[i]]],1]*priceElasticity\[Gamma]Input[[i]]*angularVelocity\[Omega][i][t-delay\[Tau]Input[[i]]],
averagingTimeInput[[i]]>0,-If[adaptationProportionalToPowerInput,Abs[powerVectorInput[[i]]],1]*priceElasticity\[Gamma]Input[[i]]/averagingTimeInput[[i]]*(angle\[Theta][i][t-delay\[Tau]Input[[i]]]-angle\[Theta][i][t-delay\[Tau]Input[[i]]-averagingTimeInput[[i]]]+averagingTimeInput[[i]]*measurementBiasInput[[i]]),
True,Print["Averaging time averagingTime has to be positive or zero."]; Return[]
],{i,1,numberOfNodes}]
];,
(*Note that the adaptation is proportional to the absolute value of the power input/output at the node*)
price[t_]:=Table[Piecewise[{
{-If[adaptationProportionalToPowerInput,Abs[powerVectorInput[[i]]],1]*adaptationRateInput*(angularVelocity\[Omega][i][t-delay\[Tau]Input[[i]]]-startConstantIntervalInput),angularVelocity\[Omega][i][t-delay\[Tau]Input[[i]]]<startConstantIntervalInput},
{0,startConstantIntervalInput<= angularVelocity\[Omega][i][t-delay\[Tau]Input[[i]]]<= endConstantIntervalInput},
{-If[adaptationProportionalToPowerInput,Abs[powerVectorInput[[i]]],1]*adaptationRateInput*(angularVelocity\[Omega][i][t-delay\[Tau]Input[[i]]]-endConstantIntervalInput),angularVelocity\[Omega][i][t-delay\[Tau]Input[[i]]]>endConstantIntervalInput}}],{i,1,numberOfNodes}];
];
With[{(*define and solve the differential equation*)
equations=Table[angle\[Theta][i]'[t]==angularVelocity\[Omega][i][t],{i,1,numberOfNodes}]\[Union]Table[inertiaVectorInput[[i]]*angularVelocity\[Omega][i]'[t]==powerVectorInput[[i]]+perturbationsInput[[i]]+price[t][[i]]-damping\[Alpha]Input[[i]]*angularVelocity\[Omega][i][t]-secondaryControlInput[[i]]*angle\[Theta][i][t]+Sum[couplingMatrixInput[[i,j]]*Sin[angle\[Theta][j][t]-angle\[Theta][i][t]+phaseShiftMatrixInput[[i,j]]],{j,1,numberOfNodes}],{i,1,numberOfNodes}]},
(*The system can be started from the fixed point, NOTE: I do not pass the Method because I assume the Method is used for NDSolve*)
If[initialConditionInput=="FixedPoint",
fixed=PowerGridFixedPoint[FilterRules[{opts}, DeleteCases[Options[PowerGridFixedPoint],Method->Automatic]]]/.{angle\[Theta]->inputAngle,angularVelocity\[Omega]->inputAngularVelocity\[Omega]};
initialConditionInput=Flatten[Table[{angle\[Theta][i][ t/;t<= 0]==inputAngle[i],angularVelocity\[Omega][i][ t/;t<= 0]==inputAngularVelocity\[Omega][i]},{i,1,numberOfNodes}]]/.fixed;];
(*Add any (initial) perturbance*)
initialConditionInput[[2,2]]+=frequencyOffsetInput;
With[{(*internally store the solution to evaluate angularVelocity\[Omega] at tmax*)
powerGridSolution=NDSolve[{equations\[Union]initialConditionInput},variables,{t,tminInput,tmaxInput},FilterRules[{opts}, Options[NDSolve]]]},
(*Export parameters and results*)
If[exportResultsInput,SetDirectory[outputDirectoryInput];
Which[
(*export as h5 format, like Potsdam people do*)
exportFormatInput=="h5",
Export[outputNameInput<>".h5",{couplingMatrixInput,powerVectorInput,Map[ToString[#,InputForm,CharacterEncoding->"ASCII"]&,initialConditionInput],If[exportPertubationsInput,Map[ToString[#,InputForm,CharacterEncoding->"ASCII"]&,perturbationsInput],Table["output prevented",{numberOfNodes}]],damping\[Alpha]Input,priceElasticity\[Gamma]Input,delay\[Tau]Input,averagingTimeInput,{tmaxInput},(Table[angularVelocity\[Omega][i][t],{i,1,numberOfNodes}]/.powerGridSolution[[1]])/.{t->tmaxInput}},{"Datasets",{"couplingMatrix","powerVector","initialCondition","perturbations","damping\[Alpha]","priceElasticity\[Gamma]","delay\[Tau]","averagingTime","tmax","angularVelocity\[Omega]Solution[tmax]"}},CharacterEncoding->"ASCII"],
(*export Mathematica specific format*)
exportFormatInput=="WDX",
Export[outputNameInput<>".wdx",{"couplingMatrix"-> couplingMatrixInput,"powerVector"->powerVectorInput,
"damping\[Alpha]"->damping\[Alpha]Input,"priceElasticity\[Gamma]"->priceElasticity\[Gamma]Input,
"delay\[Tau]"->delay\[Tau]Input,"averagingTime"->averagingTimeInput,"tmax"->tmaxInput,
"initialCondition"->initialConditionInput,
(*Perturbations and trajectory will only be exported only if their special options are set to True*)
"perturbations"->If[exportPertubationsInput,Map[ToString[#,InputForm,CharacterEncoding->"ASCII"]&,perturbationsInput],"output prevented to save memory, set 'exportPertubations'->True to export Perturbations"]
,"trajectory"->If[exportTrajectoryInput,powerGridSolution,
"output prevented to save memory, set 'exportTrajectory'->True to export Trajectory"]}
,CharacterEncoding->"ASCII"],
True, Print["exportFormat has to be 'WDX' or 'h5'"]]
];
(*Print[ToString[equations\[Union]initialConditionInput]];*)
powerGridSolution
]
]
]
]


(* ::Input::Initialization:: *)
(*Power Grid Solver with adaptive power*)
Options[PowerGridSolverAdaptivePower]=Union[Options[NDSolve] ,Options[PowerGridInput]];
PowerGridSolverAdaptivePower[opts:OptionsPattern[]]:=
Module[(*use local version of the function for the price and random initial conditions*){price,powerDynamics},
PowerGridInput[Evaluate[FilterRules[{opts}, Options[PowerGridInput]]]];

(*If this function was called from PowerGridCascadeSimulation use the reduced list of edges which does no longer contain 0-flow edges*)
listOfEdges=
If[powerGridSolverCalledByCascades,
reducedListOfEdges,
graph=AdjacencyGraph[Map[Unitize,couplingMatrixInput],VertexLabels->"Name"];
Sort[Apply[List,EdgeList[graph],2]]];
variables=Table[angle\[Theta][index],{index,1,numberOfNodes}]\[Union]Table[angularVelocity\[Omega][index],{index,1,numberOfNodes}]\[Union]Table[powerEntries[index],{index,1,numberOfNodes}];

fixed=PowerGridFixedPoint[FilterRules[{opts}, DeleteCases[Options[PowerGridFixedPoint],Method->Automatic]]]/.{angle\[Theta]->inputAngle,angularVelocity\[Omega]->inputAngularVelocity\[Omega]};
fixedPointAngles=Table[inputAngle[i],{i,1,numberOfNodes}]/.fixed;
(*The system can be started from the fixed point, NOTE: I do not pass the Method because I assume the Method is used for NDSolve*)
If[initialConditionInput=="FixedPoint",
initialConditionInput=Flatten[Table[{angle\[Theta][i][ t/;t<= 0]==inputAngle[i],angularVelocity\[Omega][i][ t/;t<= 0]==inputAngularVelocity\[Omega][i]},{i,1,numberOfNodes}]]/.fixed;];
(*Add any (initial) perturbance*)
initialConditionInput[[2,2]]+=frequencyOffsetInput;

(*attatch initial power entries, if they were not given already*)
If[Length[initialConditionInput]!= 3*numberOfNodes,
Flatten[AppendTo[initialConditionInput,Table[powerEntries[i][t/;t<=0]==powerVectorInput[[i]],{i,1,numberOfNodes}]]]];
(*Set power dynamics to be equal to zero, if no valid input is given*)
powerDynamics=Which[ListQ[powerDynamicsInput],powerDynamicsInput,
True,Table[Derivative[1][powerEntries[i]][t]==perturbationsInput[[i]],{i,1,numberOfNodes}]];
(*add perturbations to the power dynamics*)
Do[powerDynamics[[nodeIndex,2]]+=perturbationsInput[[nodeIndex]],{nodeIndex,1,numberOfNodes}];

With[{(*define and solve the differential equation*)
equations=Table[angle\[Theta][i]'[t]==angularVelocity\[Omega][i][t],{i,1,numberOfNodes}]\[Union]Table[inertiaVectorInput[[i]]*angularVelocity\[Omega][i]'[t]==powerEntries[i][t]-damping\[Alpha]Input[[i]]*angularVelocity\[Omega][i][t]-secondaryControlInput[[i]]*angle\[Theta][i][t]+Sum[dynamicCouplingMatrix[i,edgeNeighbors][t]*Sin[angle\[Theta][edgeNeighbors][t]-angle\[Theta][i][t]+phaseShiftMatrixInput[[i,edgeNeighbors]]],{edgeNeighbors,DeleteCases[Flatten[Cases[listOfEdges,{x_,y_}/;x==i\[Or]y==i]],i]}],{i,1,numberOfNodes}]\[Union]powerDynamics\[Union]Flatten[Table[{dynamicCouplingMatrix[edge[[1]],edge[[2]]][0]==couplingMatrixInput[[edge[[1]],edge[[2]]]],
dynamicCouplingMatrix[edge[[2]],edge[[1]]][0]==couplingMatrixInput[[edge[[1]],edge[[2]]]],
transientOverloadViolationTime[Position[listOfEdges,edge][[1,1]]][0]==10*tmaxInput},{edge,listOfEdges}]],

linearEquations=Table[angle\[Theta][i]'[t]==angularVelocity\[Omega][i][t],{i,1,numberOfNodes}]\[Union]Table[inertiaVectorInput[[i]]*angularVelocity\[Omega][i]'[t]==-damping\[Alpha]Input[[i]]*angularVelocity\[Omega][i][t]-secondaryControlInput[[i]]*angle\[Theta][i][t]
-Sum[dynamicCouplingMatrix[i,edgeNeighbors][t]*Cos[fixedPointAngles[[edgeNeighbors]]-fixedPointAngles[[i]]+phaseShiftMatrixInput[[i,edgeNeighbors]]]*(angle\[Theta][i][t]-fixedPointAngles[[i]]),{edgeNeighbors,DeleteCases[Flatten[Cases[listOfEdges,{x_,y_}/;x==i\[Or]y==i]],i]}]
+Sum[dynamicCouplingMatrix[i,edgeNeighbors][t]*Cos[fixedPointAngles[[edgeNeighbors]]-fixedPointAngles[[i]]+phaseShiftMatrixInput[[i,edgeNeighbors]]]*(angle\[Theta][edgeNeighbors][t]-fixedPointAngles[[edgeNeighbors]]),{edgeNeighbors,DeleteCases[Flatten[Cases[listOfEdges,{x_,y_}/;x==i\[Or]y==i]],i]}]
,{i,1,numberOfNodes}]\[Union]powerDynamics\[Union]Flatten[Table[{dynamicCouplingMatrix[edge[[1]],edge[[2]]][0]==couplingMatrixInput[[edge[[1]],edge[[2]]]],
dynamicCouplingMatrix[edge[[2]],edge[[1]]][0]==couplingMatrixInput[[edge[[1]],edge[[2]]]],
transientOverloadViolationTime[Position[listOfEdges,edge][[1,1]]][0]==10*tmaxInput},{edge,listOfEdges}]]
},
dynamicEquations=If[useLinearizedSwingInput,linearEquations,equations];
With[{(*internally store the solution to evaluate angularVelocity\[Omega] at tmax*)
powerGridSolution=NDSolve[{dynamicEquations\[Union]initialConditionInput\[Union]eventsInput},variables,{t,tminInput,tmaxInput},FilterRules[{opts}, Options[NDSolve]],DiscreteVariables->Flatten[Table[{dynamicCouplingMatrix[edge[[1]],edge[[2]]],dynamicCouplingMatrix[edge[[2]],edge[[1]]],transientOverloadViolationTime[Position[listOfEdges,edge][[1,1]]]},{edge,listOfEdges}]]]
},
(*Export parameters and results*)
If[exportResultsInput,SetDirectory[outputDirectoryInput];
Which[
(*export as h5 format, like Potsdam people do*)
exportFormatInput=="h5",
Export[outputNameInput<>".h5",{couplingMatrixInput,powerVectorInput,Map[ToString[#,InputForm,CharacterEncoding->"ASCII"]&,initialConditionInput],If[exportPertubationsInput,Map[ToString[#,InputForm,CharacterEncoding->"ASCII"]&,perturbationsInput],Table["output prevented",{numberOfNodes}]],damping\[Alpha]Input,priceElasticity\[Gamma]Input,delay\[Tau]Input,averagingTimeInput,{tmaxInput},(Table[angularVelocity\[Omega][i][t],{i,1,numberOfNodes}]/.powerGridSolution[[1]])/.{t->tmaxInput}},{"Datasets",{"couplingMatrix","powerVector","initialCondition","perturbations","damping\[Alpha]","priceElasticity\[Gamma]","delay\[Tau]","averagingTime","tmax","angularVelocity\[Omega]Solution[tmax]"}},CharacterEncoding->"ASCII"],
(*export Mathematica specific format*)
exportFormatInput=="WDX",
Export[outputNameInput<>".wdx",{"couplingMatrix"-> couplingMatrixInput,"powerVector"->powerVectorInput,
"damping\[Alpha]"->damping\[Alpha]Input,"priceElasticity\[Gamma]"->priceElasticity\[Gamma]Input,
"delay\[Tau]"->delay\[Tau]Input,"averagingTime"->averagingTimeInput,"tmax"->tmaxInput,
"initialCondition"->initialConditionInput,
(*Perturbations and trajectory will only be exported only if their special options are set to True*)
"perturbations"->If[exportPertubationsInput,Map[ToString[#,InputForm,CharacterEncoding->"ASCII"]&,perturbationsInput],"output prevented to save memory, set 'exportPertubations'->True to export Perturbations"]
,"trajectory"->If[exportTrajectoryInput,powerGridSolution,
"output prevented to save memory, set 'exportTrajectory'->True to export Trajectory"]}
,CharacterEncoding->"ASCII"],
True, Print["exportFormat has to be 'WDX' or 'h5'"]]
];
powerGridSolution
]
]
]


(* ::Input::Initialization:: *)
(*PowerGridCascadeSimulation*)
Options[PowerGridCascadeSimulation]=Options[PowerGridInput];
PowerGridCascadeSimulation[opts:OptionsPattern[]]:=
Block[{
(*If these variables are not localized, at least the lineCut variable does not work properly*)
(*lineRules,transientOverloadEvents,*)listOfEdges,trigger,fixed,initial,customPerturbations,linesCut,(*sol,*)solLineCut,plot,plotLineCut,edgesCut,graph,graphLineCut,
numberOfUnsynchronizedNodesCascade,numberOfUnsynchronizedNodesSingleFailure,numberOfLinesCut,edgeDistances,
measures,nodesNotSynchronizedCascade,nodesNotSynchronizedSingleFailure,positionsOfZeroFlow,redundantLines
},
PowerGridInput[Evaluate[FilterRules[{opts}, Options[PowerGridInput]]]];
graph=AdjacencyGraph[Map[Unitize,couplingMatrixInput],VertexLabels->"Name"];
listOfEdges=Sort[Apply[List,EdgeList[graph],2]];
(*The system starts at the fixed point*)
fixed=PowerGridFixedPoint[Evaluate[FilterRules[{opts}, Options[PowerGridFixedPoint]]]]/.{angle\[Theta]->inputAngle,angularVelocity\[Omega]->inputAngularVelocity\[Omega]};
initial=Flatten[Table[{angle\[Theta][i][ t/;t<= 0]==inputAngle[i],angularVelocity\[Omega][i][ t/;t<= 0]==inputAngularVelocity\[Omega][i],powerEntries[i][t/;t<=0]==powerVectorInput[[i]]+powerOffsetInput},{i,1,numberOfNodes}]]/.fixed;
(*determine the initial flow*)
initialFlows=Abs[Table[couplingMatrixInput[[edge[[1]],edge[[2]]]]*Sin[inputAngle[edge[[1]]]-inputAngle[edge[[2]]]+phaseShiftMatrixInput[[edge[[2]],edge[[1]]]]]/.fixed,{edge,listOfEdges}]];
(*Remove all links that do not carry any current*)
positionsOfZeroFlow=Position[initialFlows,x_/;x<10^-8];
redundantLines=listOfEdges[[Flatten[positionsOfZeroFlow]]];
(*If the trigger line is carrying no current, do not simulate*)
If[MemberQ[redundantLines,triggerLineInput],Return[{Nothing}]];

(*store the initial flow for each non-0-flow line at time=0 to compare with maximal capacity later on. Note that I delete the trigger line and any entries with very small flow.*)
initialFlows=Delete[initialFlows,Position[listOfEdges,triggerLineInput]];
(*When using the initial flow as threshold get rid of all 0-flow lines in the graph as they have effectively 0-capacity*)
If[useInitialFlowThresholdInput,
reducedListOfEdges=Delete[listOfEdges,positionsOfZeroFlow];
graph=EdgeDelete[graph,Apply[UndirectedEdge,redundantLines,2]];
initialFlows=DeleteCases[initialFlows,x_/;x<10^-8];,
reducedListOfEdges=listOfEdges;
];
reducedListOfEdgesWithoutTrigger=DeleteCases[reducedListOfEdges,triggerLineInput];
flowOfEdge[edge_]:=initialFlows[[Position[reducedListOfEdgesWithoutTrigger,edge][[1,1]]]];
(*note that reducedListOfEdges, reducedListOfEdgesWithoutTrigger, initialFlows and flowOfEdge are all to be used by the PowerGridSolver and hence should not be localized*)


(*Unprotect when Event, then the list is build correctly*)
Unprotect[WhenEvent];Attributes[WhenEvent]=DeleteCases[Attributes[WhenEvent],HoldAll];
Off[AppendTo::rvalue];

(*Generate lists of events to cut additional lines: If useInitialFlowThresholdInput is set True, the tolerance \[Alpha]\[GreaterEqual]1 is compared to the initial flow on a line. Otherwise we cut lines when a certain tolerance 0\[LessEqual]\[Alpha]\[LessEqual]1 of their capacity K is reached. To do so, we check whether minimumTransientOverloadTimeInput\[Equal]0, then the lines are cut immeadieately. Otherwise we cut the line only, if we are again (hopefully still) above the threshold*)
If[useInitialFlowThresholdInput,
(*Use initial flow as threshold*)lineRules=Flatten[Table[WhenEvent[couplingMatrixInput[[edge[[1]],edge[[2]]]]*Abs[Sin[angle\[Theta][edge[[1]]][t]-angle\[Theta][edge[[2]]][t]+phaseShiftMatrixInput[[edge[[2]],edge[[1]]]]]]>=tolerance\[Alpha]Input*flowOfEdge[edge],{dynamicCouplingMatrix[edge[[1]],edge[[2]]][t]->0,dynamicCouplingMatrix[edge[[2]],edge[[1]]][t]->0
,AppendTo[linesCut,{{edge[[1]],edge[[2]]},t}],"RemoveEvent"}],{edge,reducedListOfEdgesWithoutTrigger}]];
transientOverloadEvents={};
initialOverloadEvent={};,

verySmallNumber=10^-10;
(*lines are shut down when the flow exceeds a constant times the maximum line capacity K*)
(*If the transient time \[Equal]0, the transientOverloadEvents won't work and I have to remove the links now*)
If[minimumTransientOverloadTimeInput==0,
lineRules=Flatten[
Table[WhenEvent[
(*NOTE: I had to add a small number to the right hand side because otherwise the WhenEvent algorithm gets stiffness problems*)
Abs[Sin[angle\[Theta][edge[[1]]][t]-angle\[Theta][edge[[2]]][t]+phaseShiftMatrixInput[[edge[[2]],edge[[1]]]]]]*dynamicCouplingMatrix[edge[[1]],edge[[2]]][t]>=tolerance\[Alpha]Input*couplingMatrixInput[[edge[[1]],edge[[2]]]]+verySmallNumber,
{dynamicCouplingMatrix[edge[[1]],edge[[2]]][t]->0,dynamicCouplingMatrix[edge[[2]],edge[[1]]][t]->0
,AppendTo[linesCut,{Evaluate[{edge[[1]],edge[[2]]}],t}],"RemoveEvent"
}],{edge,reducedListOfEdgesWithoutTrigger}]];
transientOverloadEvents={};
(*At t=triggerTime check which lines are already overloaded and cut those*)
initialOverloadEvent=Flatten[
Table[WhenEvent[t>=triggerTimeInput\[And]flowOfEdge[edge]>=tolerance\[Alpha]Input*couplingMatrixInput[[edge[[1]],edge[[2]]]],{dynamicCouplingMatrix[edge[[1]],edge[[2]]][t]->0,dynamicCouplingMatrix[edge[[2]],edge[[1]]][t]->0
,AppendTo[linesCut,{Evaluate[{edge[[1]],edge[[2]]}],t}]}]
,{edge,reducedListOfEdgesWithoutTrigger}]];,

(*lines are shut down when the flow exceeds a constant times the maximum line capacity K*)
(*When the line is overloaded for the first time, the time instance is saved so that we can check in te future whether the line load violation is over*)
lineRules=Flatten[
Table[WhenEvent[
(*Check whether the line is overloaded*)
Abs[Sin[angle\[Theta][edge[[1]]][t]-angle\[Theta][edge[[2]]][t]+phaseShiftMatrixInput[[edge[[2]],edge[[1]]]]]]*dynamicCouplingMatrix[edge[[1]],edge[[2]]][t]==tolerance\[Alpha]Input*couplingMatrixInput[[edge[[1]],edge[[2]]]]+verySmallNumber,
(*If that is true, save the initial trigger time which will be tested in transientOverloadEvents*)
{If[transientOverloadViolationTime[Position[listOfEdges,edge][[1,1]]][t]<10*tmaxInput,
Evaluate[transientOverloadViolationTime[Position[listOfEdges,edge][[1,1]]][t]->10*tmaxInput],
Evaluate[transientOverloadViolationTime[Position[listOfEdges,edge][[1,1]]][t]->t]
]}],{edge,reducedListOfEdgesWithoutTrigger}]];
(*When the line ist still overloaded and the minimum time has passed, cut the link*)
transientOverloadEvents=Flatten[
Table[WhenEvent[
t-transientOverloadViolationTime[Position[listOfEdges,edge][[1,1]]][t]>= minimumTransientOverloadTimeInput,
{dynamicCouplingMatrix[edge[[1]],edge[[2]]][t]->0,dynamicCouplingMatrix[edge[[2]],edge[[1]]][t]->0
,AppendTo[linesCut,{Evaluate[{edge[[1]],edge[[2]]}],t}],"RemoveEvent"}],{edge,reducedListOfEdgesWithoutTrigger}]];
(*At t=triggerTime check which lines are already overloaded and add them to the transientOverloadEvent check list*)
initialOverloadEvent=Flatten[
Table[WhenEvent[t>=triggerTimeInput\[And]flowOfEdge[edge]>=tolerance\[Alpha]Input*couplingMatrixInput[[edge[[1]],edge[[2]]]],transientOverloadViolationTime[Position[listOfEdges,edge][[1,1]]][t]->t]
,{edge,reducedListOfEdgesWithoutTrigger}]
];
]
];
Attributes[WhenEvent]={HoldAll};Protect[WhenEvent];
(*define a trigger event which cuts one line*)
trigger={WhenEvent[t==triggerTimeInput,{dynamicCouplingMatrix[triggerLineInput[[1]],triggerLineInput[[2]]][t]->0,dynamicCouplingMatrix[triggerLineInput[[2]],triggerLineInput[[1]]][t]->0,linesCut=Append[linesCut,{triggerLineInput,t}]}]};
(*-----------------------------------------------------------------------------------------------------------*)
Off[NDSolve::precw];
(*Initially, no lines were cut*)
linesCut={};
(*Add any (initial) perturbance*)
initial[[2,2]]=frequencyOffsetInput;
(*Variable to save that the solver was called by the cascading algorithm\[Rule] will only include non-0-flow edges*)
powerGridSolverCalledByCascades=True;
sol=If[useCascadingRulesInput,
(*Cascades by cutting lines*)
PowerGridSolverAdaptivePower[MaxSteps->\[Infinity],initialCondition->"FixedPoint",events->lineRules\[Union]trigger\[Union]transientOverloadEvents\[Union]initialOverloadEvent,Evaluate[FilterRules[{opts}, Options[PowerGridSolverAdaptivePower]]]],
(*Only cut the initial line and observe the frequencies*)
PowerGridSolverAdaptivePower[MaxSteps->\[Infinity],initialCondition->"FixedPoint",events->trigger,Evaluate[FilterRules[{opts}, Options[PowerGridSolverAdaptivePower]]]]
];
edgesCut=Table[{UndirectedEdge[linesCut[[i,1]][[1]],linesCut[[i,1]][[2]]],linesCut[[i,2]]},{i,1,Length[linesCut]}];
powerGridSolverCalledByCascades=False;
(*Visualizations*)
If[generateVisualizationsInput,
plot=If[useCascadingRulesInput,
(*Plotting cutting lines*)
Plot[Table[angularVelocity\[Omega][i][t]/.sol,{i,1,numberOfNodes}],{t,0,tmaxInput},Frame->True,FrameLabel->{"time","frequency deviation","overloaded lines cut"},LabelStyle->Directive[Bold,14,FontFamily->"Arial"],PlotStyle->Thick,ImageSize->Medium,PlotRange->Full],
(*Plotting the uncontrolled case*)
Plot[Table[angularVelocity\[Omega][i][t]/.sol,{i,1,numberOfNodes}],{t,0,tmaxInput},Frame->True,FrameLabel->{"time","frequency deviation","No additional action"},LabelStyle->Directive[Bold,14,FontFamily->"Arial"],PlotStyle->Thick,ImageSize->Medium,PlotRange->Full]
];
(*plot graph with removed lines*)
graphLineCut=EdgeDelete[graph,edgesCut[[;;,1]]]];
(*Measures*)
If[calculateMeasuresInput,
(*extract the number of unsynchronized nodes*)
measures=If[useCascadingRulesInput,
nodesNotSynchronizedCascade=Table[If[Abs[((angularVelocity\[Omega][i][t]/.sol)/.{t->tmaxInput})[[1]]]>\[Omega]NodeNotSynchronizedInput,i,Nothing],{i,1,numberOfNodes}];
numberOfUnsynchronizedNodesCascade=Length[nodesNotSynchronizedCascade];
(*number of lines cut*)
numberOfLinesCut=Length[edgesCut];
(*propagation of the failure: record the time and distance of the line cut with respect to the trigger line*)
edgeDistances=Table[If[GraphDistance[graph,triggerLineInput[[1]],additionalCut[[1,1]]]==GraphDistance[graph,triggerLineInput[[2]],additionalCut[[1,2]]],{GraphDistance[graph,triggerLineInput[[1]],additionalCut[[1,1]]],additionalCut[[2]]},{GraphDistance[graph,triggerLineInput[[1]],additionalCut[[1,2]]],additionalCut[[2]]}],{additionalCut,edgesCut}];
{"number of nodes not synchronized after cascade"->numberOfUnsynchronizedNodesCascade,
"number of lines cut"->numberOfLinesCut,
"lines cut"->linesCut,
"distanceMatrix"->edgeDistances,(*"edges cut"\[Rule]edgesCut,*)"nodes not synchronized after cascade"->nodesNotSynchronizedCascade},
nodesNotSynchronizedSingleFailure=Table[If[Abs[((angularVelocity\[Omega][i][t]/.sol)/.{t->tmaxInput})[[1]]]>\[Omega]NodeNotSynchronizedInput,i,Nothing],{i,1,numberOfNodes}];
numberOfUnsynchronizedNodesSingleFailure=Length[nodesNotSynchronizedSingleFailure];
{"number of nodes not synchronized after a single line cut"->numberOfUnsynchronizedNodesSingleFailure,
"nodes not synchronized after a single line cut"->nodesNotSynchronizedSingleFailure}
];
AppendTo[measures,"redundant (0-flow) lines"-> redundantLines]
];
Which[generateVisualizationsInput,GraphicsColumn[{plot,graphLineCut}],
calculateMeasuresInput,measures,
True,Return[]]
]


(* ::Input::Initialization:: *)
(*End the "PowerGrid" Context*)
End[];
